// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // Original tutorial sidebar (you can rename this)
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Defensive Security sidebar
  defensiveSecuritySidebar: [{type: 'autogenerated', dirName: '.'}],

  // Offensive Security sidebar  
  offensiveSecuritySidebar: [{type: 'autogenerated', dirName: '.'}],

  // Writeups sidebar
  writeupsSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Tutorials sidebar
  tutorialsSidebar: [{type: 'autogenerated', dirName: '.'}],

  // You can also manually define sidebars for more control:
  /*
  defensiveSecuritySidebar: [
    'intro',
    {
      type: 'category',
      label: 'Network Security',
      items: ['network-security/firewalls', 'network-security/ids-ips'],
    },
    {
      type: 'category', 
      label: 'Endpoint Security',
      items: ['endpoint-security/antivirus', 'endpoint-security/edr'],
    },
  ],
  */
};

export default sidebars;
